# Generated by Django 5.2 on 2025-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total',
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
