# Generated by Django 5.2 on 2025-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_refundrequest_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
