# Generated by Django 5.2 on 2025-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_event_scheduled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
