# Generated by Django 5.2 on 2025-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_prize_ticket_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
