# Generated by Django 5.2 on 2025-05-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_event_organizer_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='scheduled_at',
            new_name='date',
        ),
    ]
