# Generated by Django 5.2 on 2025-09-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refundrequest_rejected_refundrequest_resolved'),
        ('app', '0006_event_image'),
    ]

    operations = [
    ]
