# Generated by Django 5.2 on 2025-09-13 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20250908_1226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('event', 'user')},
        ),
    ]
